spring.application.name=Repository_Analyzer


spring.security.oauth2.client.registration.github.client-id=Ov23liFdKuhxjrjl0bmH
spring.security.oauth2.client.registration.github.client-secret=4cc0d7248065e0a12d9f5111ea325c2f1357c0ed
spring.security.oauth2.client.registration.github.scope=repo,read:org